### ISSUE TITLE
Did you ever craft this spreadsheet into a sql view? 

### ISSUE THREAD

**Issue by johndpope** [cmenon12/bank-account-to-sheets#8]
I'm using plaid - and the way you have created the spreadsheet is amazing - rolling up totals - especially the first 3-4 columns.

**Comment by cmenon12** [comment]
Thank you! 😊 No this is all in sheets, I haven't used any SQL. Took inspiration for rolling up the totals from other ledgers, and decided to place it at the top as this was most useful to me (I didn't like having to always scroll to the bottom for it)
