### ISSUE TITLE
Error with products - error_message: 'client is not authorized to access the following products: ["transactions_refresh"]',

### ISSUE THREAD

**Issue by johndpope** [cmenon12/bank-account-to-sheets#9]

**Comment by johndpope** [comment]
https://github.com/plaid/pattern/issues/224

**Comment by cmenon12** [comment]
This is sadly a billed feature and therefore I haven't built support for it (as I'm not going to use it). https://github.com/plaid/pattern/issues/224#issuecomment-1079972174
